---
# Source: cassandra/templates/cassandra-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-cassandra
  namespace: "default"
  labels:
    app.kubernetes.io/name: cassandra
    helm.sh/chart: cassandra-9.2.7
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  cassandra-password: "Y3NkdndTeUE0cw=="
