apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: "master"
  name: elasticsearch-discovery
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: transport
      port: 9300
      protocol: TCP
  selector:
    app: elasticsearch
    component: "master"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: "client"
  name: elasticsearch-client
  namespace: default
spec:
  ports:
    - name: http
      port: 9200
      protocol: TCP
  selector:
    app: elasticsearch
    component: "client"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: "data"
  name: elasticsearch-data
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 9300
      name: transport
  selector:
    app: elasticsearch
    component: "data"