- name: "{{ create_or_delete }} configmap"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/configmap.yml') | from_yaml }}"

- name: "{{ create_or_delete }} service"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/service.yml') | from_yaml }}"

- name: "{{ create_or_delete }} deployment"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/deployment.yml') | from_yaml }}"
