- name: "{{ create_or_delete }} configmap"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/kibana/configmap.yml') | from_yaml }}"

- name: "{{ create_or_delete }} service"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/kibana/service.yml') | from_yaml }}"

- name: "{{ create_or_delete }} deployment"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/kibana/deployment.yml') | from_yaml }}"
