- name: "{{ create_or_delete }} service account"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/service-account.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} secret"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/secret.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} configmaps"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/config.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} volume"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/volume.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} statefulset"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/jenkins-controller-statefulset.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} services"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/services.yml') | from_yaml_all | list }}"

# - name: "{{ create_or_delete }} ingress"
#   kubernetes.core.k8s:
#     state: "{{ desired_state }}"
#     definition: "{{ lookup('file', 'files/jenkins-controller-ingress.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} tls context"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/tls.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} ambassador mapping"
  kubernetes.core.k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/mapping.yml') | from_yaml_all | list }}"
