- name: create configmap
  k8s_raw:
    state: present
    src: /restaurant/k8s/security/configmap.yml
- name: create service
  k8s_raw:
    state: present
    src: /restaurant/k8s/security/service.yml
- name: create deployment
  k8s_raw:
    state: present
    src: /restaurant/k8s/security/deployment.yml