version: "2"
services:
 nginx:
  extends:
   file: docker-extensions/nginx/nginx.yml
   service: nginx_common
 web:
  extends:
   file: docker-extensions/web/web.yml
   service: web_common
 dashboard:
  extends:
   file: docker-extensions/dashboard/dashboard.yml
   service: dashboard_common
 security_db:
  extends:
   file: docker-extensions/security/security_db.yml
   service: security_db_common
 security:
  extends:
   file: docker-extensions/security/security.yml
   service: security_common
  volumes:
    - "${SECURITY_VOLUM_SRC}:/var/www"
    - /var/www/node_modules
  depends_on:
    - security_db
