- hosts: master
  become: yes
  become_user: matt
  roles:
    - { role: apps/metallb, tags: metallb }
    - { role: apps/ambassador, tags: ambassador }
    - { role: apps/security-db, tags: security-db }
    - { role: apps/security, tags: security }
    - { role: apps/dashboard-be, tags: dashboard-be }
    - { role: apps/dashboard-fe, tags: dashboard-fe }
    - { role: apps/logging, tags: logging }
    - { role: apps/prometheus, tags: prometheus }
    - { role: apps/prometheus-kube-state-metrics, tags: prometheus-kube-state-metrics }
    - { role: apps/prometheus-node-exporter, tags: prometheus-node-exporter }
    - { role: apps/prometheus-alert-manager, tags: prometheus-alert-manager }
    - { role: apps/grafana, tags: grafana }
    - { role: apps/elasticsearch, tags: elasticsearch }
    - { role: apps/kibana, tags: kibana }
    - { role: apps/fluentd, tags: fluentd }
    - { role: ansible-access, tags: ansible-access }
