- hosts: master
  roles:
    - { role: apps/metallb, tags: metallb }
    - { role: apps/ambassador, tags: ambassador }
    - { role: ansible-access, tags: ansible-access }
    - { role: apps/jenkins, tags: jenkins }
    - { role: apps/argocd, tags: argocd }
