- hosts: master
  become: yes
  become_user: matt
  roles:
    - { role: apps/grafana, tags: grafana }
    - { role: apps/elasticsearch, tags: elasticsearch }
    - { role: apps/kibana, tags: kibana }
    - { role: apps/fluentd, tags: fluentd }
