- hosts: master
  become: yes
  become_user: matt

  tasks:
   - name: create local storage class
     k8s_raw:
       state: present
       src: /restaurant/k8s/security-db/local-storage-class.yml
   - name: create security-db volume
     k8s_raw:
       state: present
       src: /restaurant/k8s/security-db/mongodb-volume.yml
   - name: create security-db service
     k8s_raw:
       state: present
       src: /restaurant/k8s/security-db/service.yml
   - name: create security-db stateful set
     k8s_raw:
       state: present
       src: /restaurant/k8s/security-db/statefulset.yml
   - name: create configmap for security-app
     k8s_raw:
       state: present
       src: /restaurant/k8s/security/configmap.yml
   - name: create service for security-app
     k8s_raw:
       state: present
       src: /restaurant/k8s/security/service.yml
   - name: create deployment for security-app
     k8s_raw:
       state: present
       src: /restaurant/k8s/security/deployment.yml
   - name: create service for dashboard backend
     k8s_raw:
       state: present
       src: /restaurant/k8s/dashboard-be/service.yml
   - name: create deployment for dashboard backend
     k8s_raw:
       state: present
       src: /restaurant/k8s/dashboard-be/deployment.yml
   - name: create nginx configmap for dashboard frontend
     k8s_raw:
       state: present
       src: /restaurant/k8s/dashboard-fe/configmap.yml
   - name: create service for dashboard frontend
     k8s_raw:
       state: present
       src: /restaurant/k8s/dashboard-fe/service.yml
   - name: create deployment for dashboard frontend
     k8s_raw:
       state: present
       src: /restaurant/k8s/dashboard-fe/deployment.yml