- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: '{{ hosts_sudo_pass }}'
  roles:
    - docker
    - kube-common

- hosts: master
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: '{{ hosts_sudo_pass }}'
  roles:
    - openshift
    - certbot
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present