- hosts: master
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: '{{ hosts_sudo_pass }}'
  roles:
    - docker
    - openshift
    - certbot
    - { role: kubernetes/kube-common, tags: kube-common }
    - { role: kubernetes/master, tags: master }
