- hosts: master
  become: yes
  become_user: matt
  roles:
    - { role: apps/security-db, tags: security-db }
    - { role: apps/security, tags: security }
    - { role: apps/dashboard-be, tags: dashboard-be }
    - { role: apps/dashboard-fe, tags: dashboard-fe }
    - { role: apps/logging, tags: logging }
