- hosts: master
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: '{{ hosts_sudo_pass }}'
  gather_facts: false
  roles:
    - { role: kubernetes/kube-adm, tags: kube-adm }

- hosts: workers
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: '{{ hosts_sudo_pass }}'
  roles:
    - { role: kubernetes/preinstall, tags: preinstall }
    - docker
    - { role: kubernetes/kube-common, tags: kube-common }
    - { role: kubernetes/node, tags: node }