kind: Service
apiVersion: v1
metadata:
  name: security-app
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: security
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
