---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: "alertmanager"
  name: prometheus-alertmanager
  namespace: default
data:
  alertmanager.yml: |-
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
  amtool.yml: |-
    alertmanager.url: http://localhost:9093
    author: mandia1204@gmail.com
    output: simple