---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    component: "alertmanager"
  name: prometheus-alertmanager
  namespace: default
data:
  alertmanager.yml: |-
    global: {}
    receivers:
    - name: default-receiver
    - name: email-receiver
      email_configs:
      - to: $ALERT_GOOGLE_EMAIL
        from: $ALERT_GOOGLE_EMAIL
        smarthost: smtp.gmail.com:587
        auth_username: "$ALERT_GOOGLE_EMAIL"
        auth_identity: "$ALERT_GOOGLE_EMAIL"
        auth_password: "$ALERT_GOOGLE_PASS"
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: email-receiver
      repeat_interval: 3h
  amtool.yml: |-
    alertmanager.url: http://localhost:9093
    author: $ALERT_GOOGLE_EMAIL
    output: simple