apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    component: "alertmanager"
  name: prometheus-alertmanager
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    app: prometheus
    component: "alertmanager"
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
    component: "alertmanager"
  name: prometheus-alertmanager
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        component: "alertmanager"
    spec:
      serviceAccountName: prometheus-alertmanager
      containers:
        - name: prometheus-alertmanager
          image: "prom/alertmanager:v0.15.3"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ALERT_GOOGLE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: prometheus-alert-manager
                  key: alertGoogleEmail
            - name: ALERT_GOOGLE_PASS
              valueFrom:
                secretKeyRef:
                  name: prometheus-alert-manager
                  key: alertGooglePass

          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/data
            - --cluster.advertise-address=$(POD_IP):6783
            - --web.external-url=/

          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            {}

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/alertmanager.yml
              subPath: alertmanager.yml
            - name: config-volume
              mountPath: /etc/amtool/config.yml
              subPath: amtool.yml
            - name: storage-volume
              mountPath: "/data"
              subPath: ""

        - name: prometheus-alertmanager-configmap-reload
          image: "jimmidyson/configmap-reload:v0.2.2"
          imagePullPolicy: "IfNotPresent"
          args:
            - --volume-dir=/etc/config
            - --webhook-url=http://localhost:9093/-/reload
          resources:
            {}

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/alertmanager.yml
              subPath: alertmanager.yml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-alertmanager
        - name: storage-volume
          persistentVolumeClaim:
            claimName: prometheus-alertmanager