- name: Deploy prometheus chart
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 36.2.1
    release_namespace: prometheus
    create_namespace: yes
    binary_path: /snap/bin/helm
    state: present
    values: "{{ lookup('file', 'values.yml') | from_yaml }}"
