- name: collecting k8s cluster variables from master host
  set_fact:
    k8s_certificate_authority_data: "{{ hostvars.master.k8s_certificate_authority_data }}"
    k8s_master_ip: "{{ hostvars.master.k8s_master_ip }}"
    ansible_service_account_token: "{{ hostvars.master.ansible_service_account_token }}"

- name: generate kube-config
  become: yes
  become_user: matt
  template:
    src: templates/kube-config.j2
    dest: ~/.kube/config
    owner: matt
    group: matt
    mode: 0644
