- name: "{{ create_or_delete }} configmap"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/configmap.yml') | from_yaml }}"

- name: "{{ create_or_delete }} accounts"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/account.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} master storage objects"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/master-storage.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} data storage objects"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/data-storage.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} services"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/service.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} master statefulset"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/master-statefulset.yml') | from_yaml }}"

- name: "{{ create_or_delete }} client deployment"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/client-deployment.yml') | from_yaml }}"

- name: "{{ create_or_delete }} data statefulset"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/elasticsearch/data-statefulset.yml') | from_yaml }}"
