apiVersion: v1
kind: Secret
metadata:
  name: security-app
  namespace: default
  labels:
    app: security
type: Opaque
stringData:
  dbUserName: "{{ security_db_user }}"
  dbPassword: "{{ security_db_pass }}"
  dbAccessTokenSecret: "{{ security_access_token_secret }}"
  dbRefreshTokenSecret: "{{ security_refresh_token_secret }}"