apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-app
spec:
  selector:
    matchLabels:
      app: security
  replicas: 1
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: res-security
        image: mandia1204/securityapp:v1.0.0
        ports:
        - containerPort: 3001
        volumeMounts:
        - mountPath: /var/www/config
          name: config
      volumes:
        - name: config
          configMap:
            name: security-config
            items:
            - key: app-config
              path: default.js
