apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    component: "client"
  name: elasticsearch-client
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    component: "data"
  name: elasticsearch-data
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    component: "master"
  name: elasticsearch-master
  namespace: default