apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: default
  labels:
    app: kibana
data:
  kibana.yml: |
    elasticsearch.url: http://elasticsearch-client:9200
    server.host: "0"
    server.name: kibana
