apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  kibana_mapping
      ambassador_id: kibana
      prefix: /
      service: kibana
      timeout_ms: 9000
spec:
  type: ClusterIP
  ports:
    - name: service
      # port: 443
      port: 80
      targetPort: 5601
      protocol: TCP
  selector:
    app: kibana
