version: "2"
services:
 web_common:
  build:
   context: "${WEB_BUILD_DOCKERFILE_CTX}"
   dockerfile: "${WEB_BUILD_DOCKERFILE_NAME}"
  container_name: "${WEB_CONTAINER_NAME}"
  ports:
  - "${WEB_PORT}"
  volumes:
  - "${WEB_VOLUM_SRC}:/var/www"
  command: "${WEB_COMMAND}"
