- hosts: 127.0.0.1
  connection: local
  vars:
    variable_to_be_replaced: 'matt here'
    inline_variable: 'hello again'
    app_name: 'my-app-2'
    my_list:
        - 
          name: 'matt'
          age: 20
        -
          name: 'edson'
          age: 30
  tasks:
    - name: Ansible Template Example
      template:
        src: hello_world.j2
        dest: /home/matt/template/hello_world.txt
    - name: Ansible Template with yml
      template:
        src: config.yml
        dest: /home/matt/template/config.yml
