FROM ubuntu

MAINTAINER Marvin Andia (mandia1204@gmail.com)

COPY /windows/default-prod /opt/

COPY openssl.sh /opt/

RUN \
	apt-get update && \
	apt-get install -y nginx && \
	apt-get install -y openssl && \
	apt-get install -y dos2unix && \
	chmod 777 /opt/openssl.sh && \
	dos2unix /opt/openssl.sh && \
	/opt/./openssl.sh && \
	cp /opt/default-prod /etc/nginx/sites-available/default

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
