FROM ubuntu
MAINTAINER Marvin Andia (mandia1204@gmail.com)
COPY /unix/default /opt/
COPY openssl.sh /opt/
RUN \
	apt-get update && \
	apt-get install -y nginx && \
	apt-get install -y openssl && \
	/opt/./openssl.sh && \
	cp /opt/default /etc/nginx/sites-available/default
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
