- name: create vpc with 4 subnets
  cloudformation:
    stack_name: "mandia-eks-vpc-4subnets"
    state: "present"
    region: "us-east-2"
    disable_rollback: true
    template_body: "{{ lookup('template', 'roles/vpc-subnets/files/vpc-and-subnets.j2') }}"
    tags:
      Stack: "mandia-cloudformation-vpc"
