- name: create service account and role
  k8s_raw:
    state: present
    src: /restaurant/k8s/fluentd/account-roles.yml

- name: create configmap
  k8s_raw:
    state: present
    src: /restaurant/k8s/fluentd/configmap.yml

- name: create deployment
  k8s_raw:
    state: present
    src: /restaurant/k8s/fluentd/daemonset.yml