apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
spec:
  type: LoadBalancer
  ports:
   - name: ambassador-http
     port: 80
   - name: ambassador-https
     port: 443
     targetPort: 443
  selector:
    service: ambassador