apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: default
spec:
  type: LoadBalancer
  ports:
   - name: ambassador-http
     port: 80
   - name: ambassador-https
     port: 443
     targetPort: https
  selector:
    service: ambassador