- name: "{{ create_or_delete }} secret"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('template', 'files/secret.yml') | from_yaml }}"

- name: "{{ create_or_delete }} configmap"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/configmap.yml') | from_yaml }}"

- name: "{{ create_or_delete }} service account"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/account.yml') | from_yaml }}"

- name: "{{ create_or_delete }} storage objects"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/storage.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} service and deployment"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/service.yml') | from_yaml_all | list }}"
