apiVersion: v1
kind: Secret
metadata:
  name: prometheus-alert-manager
  namespace: default
  labels:
    app: prometheus
    component: "alertmanager"
type: Opaque
stringData:
  alertGoogleEmail: "{{ alert_google_email }}"
  alertGooglePass: "{{ alert_google_pass }}"
