- name: "{{ create_or_delete }} local storage class"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/security-db/local-storage-class.yml') | from_yaml }}"

- name: "{{ create_or_delete }} volume"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/security-db/mongodb-volume.yml') | from_yaml }}"

- name: "{{ create_or_delete }} service"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/security-db/service.yml') | from_yaml }}"

- name: "{{ create_or_delete }} stateful set"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/security-db/statefulset.yml') | from_yaml }}"
