version: "2"
services:
 security_common:
  build:
   context: "${SECURITY_BUILD_DOCKERFILE_CTX}"
   dockerfile: "${SECURITY_BUILD_DOCKERFILE_NAME}"
  container_name: "${SECURITY_CONTAINER_NAME}"
  ports:
  - "${SECURITY_PORT}"
  env_file: security.env
