- name: create service account and role
  k8s_raw:
    state: present
    src: /restaurant/k8s/ambassador/account-roles.yml

- name: create restaurant service
  k8s_raw:
    state: present
    src: /restaurant/k8s/ambassador/restaurant-service.yml

- name: create metrics service
  k8s_raw:
    state: present
    src: /restaurant/k8s/ambassador/metrics-service.yml

- name: create grafana service
  k8s_raw:
    state: present
    src: /restaurant/k8s/ambassador/grafana-service.yml

- name: create kibana service
  k8s_raw:
    state: present
    src: /restaurant/k8s/ambassador/kibana-service.yml