version: "2"
services:
 nginx_common:
  build:
    context: "${NGINX_BUILD_DOCKERFILE}"
    dockerfile: "${NGINX_DOCKERFILE_NAME}"
  container_name: "${NGINX_CONTAINER_NAME}"
  ports:
  - "${NGINX_PORT}"
