- name: "{{ create_or_delete }} service account and role"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/ambassador/account-roles.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} restaurant service"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/ambassador/restaurant-service.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} metrics service"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/ambassador/metrics-service.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} grafana service"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/ambassador/grafana-service.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} kibana service"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', '~/k8s/ambassador/kibana-service.yml') | from_yaml_all | list }}"
