- name: create configmap
  k8s_raw:
    state: present
    definition: "{{ lookup('file', '~/k8s/prometheus-alert-manager/configmap.yml') | from_yaml }}"

- name: create service account
  k8s_raw:
    state: present
    definition: "{{ lookup('file', '~/k8s/prometheus-alert-manager/account.yml') | from_yaml }}"

- name: create storage objects
  k8s_raw:
    state: present
    definition: "{{ lookup('file', '~/k8s/prometheus-alert-manager/storage.yml') | from_yaml }}"

- name: create service and deployment
  k8s_raw:
    state: present
    definition: "{{ lookup('file', '~/k8s/prometheus-alert-manager/service.yml') | from_yaml }}"
