apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ansible-access
rules:
  -
    apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - replicasets
      - serviceaccounts
      - secrets
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ansible-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ansible-access
subjects:
- kind: ServiceAccount
  name: ansible
  namespace: default
