apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: jenkins-tls-context
  namespace: default
spec:
  hosts:
    - jenkins.mandialand.com
  secret: jenkins-cert
  min_tls_version: v1.2
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: jenkins-host
  namespace: default
spec:
  hostname: jenkins.mandialand.com
  tlsSecret:
    name: jenkins-cert
  tlsContext:
    name: jenkins-tls-context
