- name: "{{ create_or_delete }} service account and role"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/account-roles.yml') | from_yaml_all | list }}"

- name: "{{ create_or_delete }} configmap"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/configmap.yml') | from_yaml }}"

- name: "{{ create_or_delete }} daemonsets"
  k8s:
    state: "{{ desired_state }}"
    definition: "{{ lookup('file', 'files/daemonset.yml') | from_yaml_all | list }}"
