apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: argocd-tls-context
  namespace: argocd
spec:
  hosts:
    - argocd.mandialand.com
  secret: argocd-cert
  min_tls_version: v1.2
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: argocd-host
  namespace: argocd
spec:
  hostname: argocd.mandialand.com
  tlsSecret:
    name: argocd-cert
  tlsContext:
    name: argocd-tls-context
