apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-server

  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards/default
      orgId: 1
      type: file

  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf
    mkdir -p /var/lib/grafana/dashboards/default
    curl -sk \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \https://grafana.com/api/dashboards/6663/revisions/1/download| sed 's|\"datasource\":[^,]*|\"datasource\": \"Prometheus\"|g' \
    > /var/lib/grafana/dashboards/default/kube-dash.json
    curl -sk \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \https://grafana.com/api/dashboards/2/revisions/2/download| sed 's|\"datasource\":[^,]*|\"datasource\": \"Prometheus\"|g' \
    > /var/lib/grafana/dashboards/default/kube-official-dash.json
    curl -sk \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \https://grafana.com/api/dashboards/1860/revisions/12/download| sed 's|\"datasource\":[^,]*|\"datasource\": \"Prometheus\"|g' \
    > /var/lib/grafana/dashboards/default/kube-node-exporter-dash.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-default
  namespace: default
  labels:
    app: grafana
    dashboard-provider: default
data: