- name: create configmap
  k8s_raw:
    state: present
    src: /restaurant/k8s/kibana/configmap.yml
- name: create service
  k8s_raw:
    state: present
    src: /restaurant/k8s/kibana/service.yml
- name: create deployment
  k8s_raw:
    state: present
    src: /restaurant/k8s/kibana/deployment.yml