- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - { role: vpc-subnets, tags: vpc-subnets }
    - { role: eks-cluster, tags: eks-cluster }
    - { role: eks-worker-nodes, tags: eks-worker-nodes }
